codegen:
	quicktype -s schema ./sandbox/specs/sandbox.json -o ./sandbox/generated/sandbox.py
	quicktype -s schema ./sandbox/specs/person.json -o ./sandbox/generated/person.py

install:
	poetry install
